apiVersion: apps/v1
kind: Deployment
metadata:
  name: smart-light
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smart-light
  template:
    metadata:
      labels:
        app: smart-light
    spec:
      containers:
      - name: smart-light
        image: smart-light:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: thermostat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thermostat
  template:
    metadata:
      labels:
        app: thermostat
    spec:
      containers:
      - name: thermostat
        image: thermostat:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5002
---
apiVersion: v1
kind: Service
metadata:
  name: smart-light-service
spec:
  type: NodePort
  selector:
    app: smart-light
  ports:
  - port: 5001
    targetPort: 5001
    nodePort: 30001
---
apiVersion: v1
kind: Service
metadata:
  name: thermostat-service
spec:
  type: NodePort
  selector:
    app: thermostat
  ports:
  - port: 5002
    targetPort: 5002
    nodePort: 30002